name: Build, Push, and Deploy Personal Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --- JOB 1: CONSTRUIR Y SUBIR LA IMAGEN DOCKER ---
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: smarquezp/sergio-personal-agent:latest, smarquezp/sergio-personal-agent:${{ github.sha }}

  # --- JOB 2: DESPLEGAR EN EL SERVIDOR ---
  deploy-on-vps:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Copiar index.html al servidor (frontend)
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "nginx/index.html"
          target: "/home/ubuntu/sergio-personal-agent/index.html"

      - name: Copiar update.sh y docker-compose.yml al servidor (backend)
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "nginx/update.sh,nginx/docker-compose.yml"
          target: "/home/ubuntu/sergio-personal-agent/"

      - name: Copiar nginx.conf al servidor (nginx config)
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "nginx/nginx.conf"
          target: "/home/ubuntu/sergio-personal-agent/nginx.conf"

      - name: Deploy to server by running the update script
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/sergio-personal-agent
            chmod +x ./update.sh
            bash ./update.sh
            sudo mv /home/ubuntu/sergio-personal-agent/nginx.conf /etc/nginx/sites-available/chat.sergiomarquez.dev
            sudo mv /home/ubuntu/sergio-personal-agent/index.html /var/www/chat.sergiomarquez.dev/index.html
            sudo systemctl restart nginx
